### DISCUSSION TITLE
Deploy using GitHub Actions when using a Turborepo monorepo.

### DISCUSSION THREAD

**Discussion by j-fdion** [triggerdotdev/trigger.dev#1471] [Q&A] [answered]
Hi! I'm using turborepo with pnpm.

My project has the following structure based on [https://github.com/t3-oss/create-t3-turbo](url) :

.github/
apps/nextjs-app
packages/api
packages/db
packages/trigger <--- my trigger.dev project is here

How I can adapt the GitHub action file to match my project structure. Has anyone done this before?

Thanks!

**Comment by j-fdion** [comment, marked as answer]
Here's a working solution:

I add this step in my github action file.

```
    trigger:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v4
  
        - name: Setup
          uses: ./tooling/github/setup
  
        - name: Deploy Trigger.dev
          working-directory: ./packages/trigger
          env:
            TRIGGER_ACCESS_TOKEN: ${{ secrets.TRIGGER_ACCESS_TOKEN }}
          run: pnpm dlx trigger.dev@latest deploy --env staging
```
