### ISSUE TITLE
bug: when the image fails to be pulled from the registry, the deployment hangs

### ISSUE THREAD

**Issue by ghostdevv** [triggerdotdev/trigger.dev#1476]
### Provide environment information

n/a

### Describe the bug

I have a self-hosted registry for trigger exclusively, and I noticed while debugging the setup that when the image failed to be pulled the task just kept going seemingly unaware. I can't recall if this happened when the image was missing, but it definitely happened if the authentication failed.	

### Reproduction repo

n/a

### To reproduce

Self host a registry, and use it with trigger. I'd try kicking it offline, and if that error does appear in the task logs then try adding auth to the registry but not the docker-provider container. Self hosting the registry was rather simple with docker:

```yaml
  trigger-registry:
    container_name: trigger-registry
    image: registry:2
    restart: always
    volumes:
      - ./rdata:/var/lib/registry
      - ./auth:/auth
 ```

See [the guide on built-in auth](https://distribution.github.io/distribution/about/deploying/#native-basic-auth) if you need.
